Was grandma right, is it really the phone?
Intro - Zoja
- present the dataset
users/non users - percentage - men/women side to side
most used apps - pie/bar chart
occupation status - pie/bar chart
"best" of the social media user categories
    - rest mention as a category (these people were asked these questions)


- present the story telling


Clustering of the users - Sofia
- doom scroller, professional, validation - hover over to see the affiliation (details of the points)
- people love being clustered

Are the stereotypes true?interactive - Zoja
- ig = validation
- redit = sleep?
etc.

Mood shifting over screen time - interactive? - Sofia



COMPARE TO THE NON USER
make it a diagnosis tool
Closing line: "So was grandma right? Mostly. But she was also scrolling Facebook the whole time she said it."

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('../data/smmh.csv')
data.head()

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1

In [5]:
data['Gender_Grouped'] = data['2. Gender'].replace({
    'Nonbinary ': 'Non-binary',
    'Non-binary': 'Non-binary',
    'NB': 'Non-binary',
    'Non binary ': 'Non-binary',
    'Male': 'Male',
    'Female': 'Female',
    'unsure ': 'Other',
    'Trans': 'Other',
    'There are others???': 'Other'
})
print(data['Gender_Grouped'].unique())

<StringArray>
['Male', 'Female', 'Non-binary', 'Other']
Length: 4, dtype: str

In [4]:
print("\n".join(data.columns.astype(str)))

Timestamp
1. What is your age?
2. Gender
3. Relationship Status
4. Occupation Status
5. What type of organizations are you affiliated with?
6. Do you use social media?
7. What social media platforms do you commonly use?
8. What is the average time you spend on social media every day?
9. How often do you find yourself using Social media without a specific purpose?
10. How often do you get distracted by Social media when you are busy doing something?
11. Do you feel restless if you haven't used Social media in a while?
12. On a scale of 1 to 5, how easily distracted are you?
13. On a scale of 1 to 5, how much are you bothered by worries?
14. Do you find it difficult to concentrate on things?
15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?
16. Following the previous question, how do you feel about these comparisons, generally speaking?
17. How often do you look to seek validation from features of social media?
18. How often do you feel depressed or down?
19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?
20. On a scale of 1 to 5, how often do you face issues regarding sleep?

In [7]:
# Filter for respondents who replied "no" to question 6 (Do you use social media?)
non_users = data[data['6. Do you use social media?'].str.lower().str.strip() == 'no']
print(f"Number of non-users: {len(non_users)}")
print("\nNon-users data:")
non_users

Number of non-users: 3

Non-users data:

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?",Gender_Grouped
9,4/18/2022 19:41:34,20.0,Male,Single,University Student,University,No,"Reddit, Pinterest",Less than an Hour,1,...,1,1,1,1,1,1,1,1,1,Male
54,4/18/2022 22:35:53,26.0,Male,In a relationship,Salaried Worker,Company,No,"YouTube, Discord, Reddit",Between 1 and 2 hours,4,...,2,2,1,1,3,1,1,3,2,Male
134,4/19/2022 22:04:03,50.0,Male,Divorced,Salaried Worker,Private,No,"Instagram, YouTube",Between 1 and 2 hours,2,...,2,2,2,1,4,1,2,2,1,Male

In [8]:
# Summary of non-users
print("Summary of non-users:")
print(non_users[['1. What is your age?', '2. Gender', '3. Relationship Status', '4. Occupation Status']].to_string())

Summary of non-users:
     1. What is your age? 2. Gender 3. Relationship Status 4. Occupation Status
9                    20.0      Male                 Single   University Student
54                   26.0      Male      In a relationship      Salaried Worker
134                  50.0      Male               Divorced      Salaried Worker

In [ ]:
# Display all columns for non-users
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
print("All data for non-users:")
print(non_users.to_string())